import models.Branch;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Globals {
    public static List<Branch> branchList = new ArrayList<>();

    /**
     * This method parses the File input to list of strings.
     *
     * @return a list of strings generated by parsing the file.
     * @throws FileNotFoundException, when file is not found.
     */
    public static List<String> takeFileInput() throws FileNotFoundException {
        List<String> inputList = new ArrayList<>();
        File file = new File("C:\\Users\\toshi\\Desktop\\input.txt");
        Scanner sc = new Scanner(file);
        while (sc.hasNextLine()) {
            inputList.add(sc.nextLine());
        }

        return inputList;
    }
}
